version: '3'
services:
  springbootapp:
    container_name: todo-mysql-docker-compose
    image: todo-mysql-docker
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/decodingcloud?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
  mysqldb:
    container_name: tododb
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: decodingcloud